// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJkkHtIz09xmVaeXTWvlhuxhXI_EmwYbY',
    appId: '1:130589907840:web:67d25328aaaf82aafbff65',
    messagingSenderId: '130589907840',
    projectId: 'flutterfirebasewebsocketchat',
    authDomain: 'flutterfirebasewebsocketchat.firebaseapp.com',
    storageBucket: 'flutterfirebasewebsocketchat.appspot.com',
    measurementId: 'G-D2FX3CCY40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYUO3geNXWkvvtMJaLVlQTySQSdqxK4Oo',
    appId: '1:130589907840:android:ed112feddd9bee36fbff65',
    messagingSenderId: '130589907840',
    projectId: 'flutterfirebasewebsocketchat',
    storageBucket: 'flutterfirebasewebsocketchat.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJkkHtIz09xmVaeXTWvlhuxhXI_EmwYbY',
    appId: '1:130589907840:web:ee65d9c838f17d9afbff65',
    messagingSenderId: '130589907840',
    projectId: 'flutterfirebasewebsocketchat',
    authDomain: 'flutterfirebasewebsocketchat.firebaseapp.com',
    storageBucket: 'flutterfirebasewebsocketchat.appspot.com',
    measurementId: 'G-TRR65BM9VS',
  );
}
